package by.uniqo.bot.botapi.handlers;

/**Возможные состояния бота
 */

public enum BotState {
    ASK_START,
    ASK_TOTALNUMBER,
    ASK_TAPESCOLOR,
    ASK_MODELNUMBER,
    ASK_COLOROFMODELTEXT,
    ASK_SYMBOLNUMBER,
    ASK_NUMBEROFMEN,
    ASK_NUMBEROFWOMEN,
    ASK_NUMBEROFTEACHERS,
    ASK_SCHOOLNUMBER,
    ASK_ADDITIONALSERVICES,
    ASK_LITTLEBELL,
    ASK_LITTLEBELLCOLOR,
    ASK_BIGBELL,
    ASK_BIGBELLCOLOR,
    ASK_STARS,
    ASK_SCROLL,
    ASK_SCROLLCOLOR,
    ASK_RIBBON,
    ASK_RIBBONCOLOR,
    ASK_BOWTIE,
    ASK_BOWTIECOLOR,
    ASK_CREDENTIALS,
    ASK_PHONENUMBER,
    ASK_URLVK,
    ASK_DELIVERYADDRESS,
    ASK_COMMENTSTOORDER,
    FILLING_ORDER,
    ORDER_FILLED,
    SHOW_USER_ORDER,
    SHOW_MAIN_MENU,
    SHOW_HELP_MENU
}
